### ISSUE TITLE
ArgumentError: couldn't find HOME environment -- expanding `~'  - for container rake commands

### ISSUE THREAD

**Issue by dashbitla** [alienfast/elastic-beanstalk#45]
Here is my eb.yml configuration ... 

```
  03-rake.config:
    container_commands:
      01-db-seed:
        command: "rake db:seed --trace"
        leader_only: true
      02-seed-privilges:
        command: "rake seed:privileges --trace"
        leader_only: true
```

It fails with the followirng error in /var/log/eb-activity.log 

```
 ArgumentError: couldn't find HOME environment -- expanding `~'
  /opt/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/simplecov-0.9.1/lib/simplecov/defaults.rb:87:in `expand_path'
  /opt/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/simplecov-0.9.1/lib/simplecov/defaults.rb:87:in `<top (required)>'
  /opt/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/simplecov-0.9.1/lib/simplecov.rb:140:in `require'
  /opt/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/simplecov-0.9.1/lib/simplecov.rb:140:in `<top (required)>'
  /opt/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.9.6/lib/bundler/runtime.rb:76:in `require'
  /opt/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.9.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
  /opt/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.9.6/lib/bundler/runtime.rb:72:in `each'
  /opt/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.9.6/lib/bundler/runtime.rb:72:in `block in require'
  /opt/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.9.6/lib/bundler/runtime.rb:61:in `each'
  /opt/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.9.6/lib/bundler/runtime.rb:61:in `require'
  /opt/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.9.6/lib/bundler.rb:134:in `require'
  /var/app/ondeck/config/application.rb:13:in `<top (required)>'
  /opt/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  /opt/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  /var/app/ondeck/Rakefile:5:in `<top (required)>'
  /opt/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-11.1.2/lib/rake/rake_module.rb:28:in `load'
  /opt/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-11.1.2/lib/rake/rake_module.rb:28:in `load_rakefile'
  /opt/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-11.1.2/lib/rake/application.rb:689:in `raw_load_rakefile'
  /opt/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-11.1.2/lib/rake/application.rb:94:in `block in load_rakefile'
  /opt/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
  /opt/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-11.1.2/lib/rake/application.rb:93:in `load_rakefile'
```

**Comment by rosskevin** [comment]
Your error seems unrelated to this gem.  We do all the work on the packaging side, nothing when it is actually deployed on the eb server.

As an FYI - I think you should probably restrict `simplecov` so it isn't in your server's runtime environment.
