### ISSUE TITLE
VPC security group "does not exist"

### ISSUE THREAD

**Issue by dcrockwell** [alienfast/elastic-beanstalk#53]
```
Aws::ElasticBeanstalk::Errors::ConfigurationValidationException: Configuration validation exception: Invalid option value: 'sg-xxxxxxxx' (Namespace: 'aws:autoscaling:
launchconfiguration', OptionName: 'SecurityGroups'): The security group 'sg-xxxxxxxx' does not exist
/Users/dcrockwell/.rvm/gems/ruby-2.3.3/gems/aws-sdk-core-2.6.35/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
/Users/dcrockwell/.rvm/gems/ruby-2.3.3/gems/aws-sdk-core-2.6.35/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
/Users/dcrockwell/.rvm/gems/ruby-2.3.3/gems/aws-sdk-core-2.6.35/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
/Users/dcrockwell/.rvm/gems/ruby-2.3.3/gems/aws-sdk-core-2.6.35/lib/seahorse/client/plugins/response_target.rb:21:in `call'
/Users/dcrockwell/.rvm/gems/ruby-2.3.3/gems/aws-sdk-core-2.6.35/lib/seahorse/client/request.rb:70:in `send_request'
/Users/dcrockwell/.rvm/gems/ruby-2.3.3/gems/aws-sdk-core-2.6.35/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
/Users/dcrockwell/.rvm/gems/ruby-2.3.3/gems/eb_deployer-0.6.6/lib/eb_deployer/aws_driver/beanstalk.rb:37:in `update_environment'
/Users/dcrockwell/.rvm/gems/ruby-2.3.3/gems/eb_deployer-0.6.6/lib/eb_deployer/throttling_handling.rb:13:in `block in method_missing'
/Users/dcrockwell/.rvm/gems/ruby-2.3.3/gems/eb_deployer-0.6.6/lib/eb_deployer/utils.rb:13:in `backoff'
/Users/dcrockwell/.rvm/gems/ruby-2.3.3/gems/eb_deployer-0.6.6/lib/eb_deployer/throttling_handling.rb:12:in `method_missing'
/Users/dcrockwell/.rvm/gems/ruby-2.3.3/gems/eb_deployer-0.6.6/lib/eb_deployer/eb_environment.rb:107:in `block in update_eb_env'
/Users/dcrockwell/.rvm/gems/ruby-2.3.3/gems/eb_deployer-0.6.6/lib/eb_deployer/eb_environment.rb:128:in `with_polling_events'
/Users/dcrockwell/.rvm/gems/ruby-2.3.3/gems/eb_deployer-0.6.6/lib/eb_deployer/eb_environment.rb:106:in `update_eb_env'
/Users/dcrockwell/.rvm/gems/ruby-2.3.3/gems/eb_deployer-0.6.6/lib/eb_deployer/eb_environment.rb:26:in `deploy'
/Users/dcrockwell/.rvm/gems/ruby-2.3.3/gems/eb_deployer-0.6.6/lib/eb_deployer/deployment_strategy/inplace_update.rb:12:in `deploy'
/Users/dcrockwell/.rvm/gems/ruby-2.3.3/gems/eb_deployer-0.6.6/lib/eb_deployer/default_component.rb:16:in `deploy'
/Users/dcrockwell/.rvm/gems/ruby-2.3.3/gems/eb_deployer-0.6.6/lib/eb_deployer/environment.rb:32:in `block in deploy'
/Users/dcrockwell/.rvm/gems/ruby-2.3.3/gems/eb_deployer-0.6.6/lib/eb_deployer/environment.rb:31:in `each'
/Users/dcrockwell/.rvm/gems/ruby-2.3.3/gems/eb_deployer-0.6.6/lib/eb_deployer/environment.rb:31:in `deploy'
/Users/dcrockwell/.rvm/gems/ruby-2.3.3/gems/eb_deployer-0.6.6/lib/eb_deployer.rb:233:in `deploy'
```

* This only seems to be an issue when using a security group from a VPC.
* If I use an SG that is not associated with a VPC it works as expected.
* The SG definitely exists in the VPC
* Had to use the sg-xxxxxxxx id instead of the name, as AWS doesn't accept SG names for VPC; only ids.

**Comment by rosskevin** [comment]
If I read the stack correctly, this doesn't seem to be a problem with this project, but perhaps either an invalid config specified by you, or a bug upstream in the config validation such as aws-sdk-core.

You'll have to dig in and figure this out. I would start in the middle with the eb_deployer docs as they may address this situation. Note that we are a simple dry rake wrapper around eb_deployer.  If not, you'll have to continue upstream to aws-sdk-core.

When investigating matters like this, running the rake task in the debugger is quite helpful.

**Comment by dcrockwell** [comment]
Thanks for the leads. I'll keep digging :)
